### ISSUE TITLE
Filtering/Searching for Bean Items

### ISSUE THREAD

**Issue by jonnykry** [lcollin/warehouse#4]
# Issue

We require a way to filter/search bean items on the frontend.  I think that the logic for this belongs on the backend via the API call.

Requirements for this iteration are searching for beans by name and sorting by:
- Name (asc. / desc. alphabetically)
- Cost (asc. / desc.)

My initial thought for the API is something along the lines of:  `api/item?searchTerm=val&filterName=0&filterCost=1` where 0 / 1 are flags for asc/desc.  If the params aren't passed, we don't do any filtering or searching.

**Comment by ghmeier** [comment]
Should be fixed [in this commit](https://github.com/lcollin/warehouse/commit/4ab2ac0a57095533ab49fc1d54b372c9890072e0)

The actual api call will be `api/item?q=<value>&name=0&cost=1`
