### ISSUE TITLE
Get User and Roaster information from Towncenter

### ISSUE THREAD

**Issue by yuderekyu** [lcollin/warehouse#5]
To create a shipping label, we need to get User and Roaster attributes from Towncenter using the gateway. After obtaining this information, we can successfully post the information to Shippo to start the label creation process.

**Comment by ghmeier** [comment]
@yuderekyu check here for where to create the label: https://github.com/lcollin/warehouse/blob/master/helpers/order.go#L99

**Comment by ghmeier** [comment]
There's a new TC endpoint that gets a user from roasterID, would that be helpful or simplify things here?

Not sure if it's relevant, but i thought i'd mention it.

**Comment by yuderekyu** [comment]
That would let the request have one less attribute, since I'm currently expecting `userId` and `roasterId` within the request to to get user and roaster information. I'd still have to make two calls to TC though.

**Comment by ghmeier** [comment]
ah ok, well the api is there if it helps, but doesn't look like it's too essential
