### ISSUE TITLE
Add itemID to Orders

### ISSUE THREAD

**Issue by yuderekyu** [lcollin/warehouse#8]
Because of the deprecated `SubOrder`, `Order` currently does not store `itemID`. Add `itemID` to `Order`, to allow Covenant also pass this attribute in, when creating an Order.
https://github.com/yuderekyu/covenant/issues/8

**Comment by ghmeier** [comment]
@yuderekyu are you working on this? i could add it real quick

**Comment by yuderekyu** [comment]
Ah, I forgot to assign myself this, yeah I added it to my branch so it's all good

**Comment by ghmeier** [comment]
sweet :) and it's added to the db?

**Comment by yuderekyu** [comment]
Yup! I forgot to add it to our sql config scripts though
